manager:
  port: 8081
  jwtSecret: "123456"
  env: "devlopment"
  accessExpire: 86400
  refreshExpire: 604800
db:
  host: "121.40.97.230"
  port: 3307
  username: "root"
  password: "admin@888"
  database: "basketball"
redis:
  host: "121.40.97.230"
  port: 6381
  password: ""
  db: 0